### ISSUE TITLE
Browser does not send Origin for GET requests from fetch and XHR

### ISSUE THREAD

**Issue by gsahbi** [curityio/oauth-agent-node-express#17]
This assumption that all modern browsers send Origin by default is not true.

https://github.com/curityio/oauth-agent-node-express/blob/510154bf33dc4119bfaf8f48a5ca46dfabf59640/src/lib/validateRequest.ts#L23

And so getClaims and getUserInfo fail.

As per MDN documentation of fetch API https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

Quote:

Broadly speaking, user agents add the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) request header to:

- [cross origin](https://developer.mozilla.org/en-US/docs/Glossary/CORS) requests.
- [same-origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) requests except for [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) or [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests (i.e. they are added to same-origin [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST), [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS), [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH), and [DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE) requests).

End Quote

**Comment by gary-archer** [comment]
In same site setups you can set an environment variable of `CORS_ENABLED='false'` to fix this. This turns off any cross origin behavior or setting of CORS headers. You should also set the equivalent setting in the [oauth proxy nginx module](https://github.com/curityio/nginx_oauth_proxy_module#oauth_proxy_cors_enabled).

Our default deployment uses sibling domains for web static content and token handler components. If you want to avoid this, eg to reduce the overhead of CORS pre-flight requests, you would overwrite our [example SPA deployment](https://github.com/curityio/spa-using-token-handler/blob/main/deploy.sh#L19) like this, and the above environment variable is then set:

```bash
export BASE_DOMAIN='example.com'
export WEB_SUBDOMAIN='www'
export API_SUBDOMAIN='www'
export IDSVR_SUBDOMAIN='login'
```
